---
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  linux:
    name: Go CI (Linux)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install mise
        uses: jdx/mise-action@v4

      - name: Run CI
        run: task ci

  macos:
    name: Go CI (macOS)
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install mise
        uses: jdx/mise-action@v4

      - name: Run CI
        run: task ci
